language: python
python:
  - "3.6"
before_install:
  - sudo apt-get install -y upx-ucl
install:
  - pip install pyinstaller
script:
  - make dist
after_script:
  - ls -l
  - sha512sum borgmatic-*-*.tar.gz
  - sha256sum borgmatic-*-*.tar.gz
  - sha1sum borgmatic-*-*.tar.gz
  - md5sum borgmatic-*-*.tar.gz
deploy:
  provider: releases
  api_key: "GITHUB OAUTH TOKEN"
  file: "borgmatic-*-*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    repo: cmarquardt/borgmatic-binary
