language: python
python:
- '3.5'
before_install:
- sudo apt-get install -y upx-ucl
install:
- pip install pyinstaller
script:
- make dist
after_script:
- ls -l
- sha512sum borgmatic-*-*.tar.gz
- sha256sum borgmatic-*-*.tar.gz
- sha1sum borgmatic-*-*.tar.gz
- md5sum borgmatic-*-*.tar.gz
before_deploy:
- export RELEASE_FILE=$(ls borgmatic-*-*.tar.gz)
- echo "Deploying $RELEASE_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: sb2oxvhRykxF9IBzQyyzGHhuGZO8r3KvT2dTyP2v8vf/uQ4x7KsYxYM0lBf8+g2+FO53Rhee6eUOvz5lcXmS2Pm+GEIu4gYb99M4H7dDrWoMISelbzBmgN7Z9FVLt8MdHh1zrqeIP/HOaoI5l2Q7iJoZ/iGTQFey5dItRbDVPJYkCIWPPYLNd3ms/0cdLVsbGDLl0K/EwQsIaqeJ+TXxa6QFMZaFnX9yVpTsHceakvFNnCMA+v9/8d9QH6CGwOXlGs60DPPeo6J8NeGZ/n3V3STmV7Nmz3qLi/b10YwWGOw1EU10S/mYh9onLXjbDKg9b1wmwy0qkjeuaOITMdj7u3AyLcyR39sVp1LIwlCb8P2U13bv0EgNX6RWLRsS3ahm0en7i/CUSJ4kC4aRu0X+eMnRUNFH8s/9tyWx0BM3w61gudJVMBD1dfisHQjhLGvjLpSJ7Nzf4pItIJFDLXoNFji196LWYUhmD+CL4nFSVVNYRibarHAE5Wn9TdFhA1+Y5NFfJYic6NIvcH8DS/UIiS3CijU78ZosDMfVRzoOW9/MjWHiR4gu+Yu+0iNC6GHInaO8xPzWOazBikwqDSicJIJVBZF5GIakT6KxXtRX5sJQycuZO8G4+JG1w6kWEZExQpTv9w3X6sWm04/+JyJOxhhk1OVlY1ysYTbWUu7m4wo=
  file_glob: true
  file: ${RELEASE_FILE}
  skip_cleanup: true
  on:
    tags: true
    repo: cmarquardt/borgmatic-binary
